### ISSUE TITLE
utils/shape.latte jako Latte filtr

### ISSUE THREAD

**Issue by enzy** [manGoweb/MangoPress#104]
`{example|shape}`
`{example|shape:customClass}`

instead of

`{include utils/shape.latte name => example, class => customClass}`

**Comment by DNepovim** [comment]
Jako že uložíš do promněné název shape a ten pak filtruješ? To máš zbytečně o řádek víc.
Možná spíš makro než filtr, ne?

**Comment by enzy** [comment]
předpokládal jsem, že latte umí inline string, pokud ne, tak: `{'example'|shape}

**Comment by DNepovim** [comment]
Do bude latte ignorovat a vytiskne to jak jsi to napsal.

**Comment by ViliamKopecky** [comment]
`{=example|shape}` by slo

A nebo udelat to makro (coz je jen o trochu slozitejsi) jako treba `{shape example customClass}`

**Comment by enzy** [comment]
Tak sem nějak sesmolil marko:
```php
MangoMacros::$set['shape'] = function(\Latte\MacroNode $node, \Latte\PhpWriter $writer) {
	$param = $node->args;
	$params = explode(',', $param);
	$name = isset($params[0]) ? '"' . trim($params[0]) . '"' : '""';
	$class = isset($params[1]) ? '"' . trim($params[1]) . '"' : '""';

	return $writer->write("echo '<svg class=\"shape shape-' . %escape($name) . ' ' . %escape($class) .'\"><use xlink:href=\"#shape-' . %escape($name) . '\"/></svg>';");
};
```

Použití:
```
{shape nazev}
{shape nazev, dalsi CSS tridy}
{shape $ico}
{shape $ico, iconList-icon}
```

@ViliamKopecky @DNepovim

**Comment by enzy** [comment]
Ještě vylepšená verze od Davida:
```php
MangoMacros::$set['shape'] = function(\Latte\MacroNode $node, \Latte\PhpWriter $writer) {
	$name = $writer->formatWord($node->tokenizer->fetchWord());
	
	return $writer->write("echo '<svg class=\"shape shape-' . %escape($name) . ' ' . %escape(implode(\" \", %node.array)) .'\"><use xlink:href=\"#shape-' . %escape($name) . '\"/></svg>';");
};
```

kde i další CSS třídy mohou být z proměnných, ale už se musejí povinně oddělovat čárkou:

```
{shape nazev}
{shape nazev, dalsi, CSS, tridy}
{shape $ico}
{shape $ico, iconList-icon, $ico}
```

**Comment by ViliamKopecky** [comment]
Bude tam fungovat. Asi otázka na Davida.

```
{shape nazev, $neco ? foo : bar, CSS, (necojinyho|latte_filtr)}
```

**Comment by enzy** [comment]
To fakt netuším, ale i @matej21 byl v tom dost ztracenej 😂

**Comment by DNepovim** [comment]
Mě se ta vylepšená verze moc nepáčí. Třídy bych tam radši dával jako jeden string, nebo array (spíš string). Tohle mi přijde divné. Radši bych tam dal třetí parametr pro id. To se taky občas hodí.

**Comment by enzy** [comment]
A ještě za mě přidávám důležitou věc, na kterou jsem zapomněl: Možnost předat obsah `<title />`

**Comment by enzy** [comment]
> Radši bych tam dal třetí parametr pro id

S ID nesouhlasím, to by ikona neměla potřebovat. Dá se obejít obalovacím prvkem s ID či strukturou, kterou budeš potřebovat.

**Comment by matej21** [comment]
@ViliamKopecky imho by to melo jit

**Comment by matej21** [comment]
btw, id by slo resit takhle, pokud by se z tohohle udelalo n makro
```latte
<svg n:shape="foo anotherClass" id="bar"/>
