### ISSUE TITLE
Nette\Object is deprecated

### ISSUE THREAD

**Issue by enzy** [manGoweb/MangoPress#114]
> Deprecated: Replace deprecated Nette\Object with trait Nette\SmartObject in app/Container.php:7 in vendor/nette/utils/src/loader.php on line 10

Is this fix okay?

```php
class Container {
	use Nette\SmartObject;
```

**Comment by HonzaMatosik** [comment]
@enzy @ViliamKopecky Nějaký update zde? Taky bych to potřeboval vyřešit

**Comment by ViliamKopecky** [comment]
Jo, myslim že by to mělo s tímhle fixem být v pohodě :)
