### ISSUE TITLE
Move dependencies from mango.yaml

### ISSUE THREAD

**Issue by MekliCZ** [manGoweb/MangoPress#133]
Because `mango install` is being deprecated in mango-cli 2.2.0 (https://github.com/manGoweb/mango-cli/commit/be9e68ae0bbb113ec87268acf377690c54a20b61) and only `npm install` (or `yarn`) should be used, I would move dependencies from `mango.yaml` to `package.json`. I'm happy to make PR.

**Comment by ViliamKopecky** [comment]
I think @JirkaVebr has frontend refactorings for mangopress in works, including this.

**Comment by ViliamKopecky** [comment]
makes sense, you can make a PR, @MekliCZ ;)
