### ISSUE TITLE
Dont rely on global `composer`

### ISSUE THREAD

**Issue by ViliamKopecky** [manGoweb/MangoPress#150]
Include (or download when needed) `composer.phar` in repo

**Comment by enzy** [comment]
Why not?

Dne út 31. 7. 2018 8:57 uživatel Viliam Kopecký <notifications@github.com>
napsal:

**Comment by ViliamKopecky** [comment]
Based on newbe's first experience with mangopress. Not everybody has composer installed, more so globally exactly as `composer`
