### ISSUE TITLE
metabox get_field for image type doesnt work

### ISSUE THREAD

**Issue by hexcross** [manGoweb/MangoPress#46]
If you use {$images = get_field(get_the_ID(), 'm_images')} it doesnt work correctly, this variable wasnt converted to array.

Quick solution: rwmb_meta( 'm_images', 'type=image&size=product_thumb' )

**Comment by ViliamKopecky** [comment]
Fixed in https://github.com/manGoweb/MangoPress/commit/b896a79fd5f278af389a26fb11660fa322ea7cdd

`get_field` (or alias `meta`) returns just the single value, if you have gallery, or other meta field with multiple values, use `get_field_array` or `meta_array`.
