### ISSUE TITLE
Sync frontend structure with mango-cli-example

### ISSUE THREAD

**Issue by enzy** [manGoweb/MangoPress#70]
- [x] SASS
- [ ] new JS components
- [x] same file structure, adding only specific WP files
- [ ] include sample Jade templates for a styleguide first workflow
- [ ] update mango-cli to the latest version

**Comment by Onset** [comment]
What is the reason to build a styleguide in Jade when the rest runs on latte? It makes reuses between these two complicated.

**Comment by enzy** [comment]
Speed, speed, speed... as it's faster to get prototype running on a static stack with Jade than with any dynamic language (and which also requires more syntax to type)

Further in a project lifecycle it can function as an original reference. But that doesn't mean it needs to be updated every time.
