### ISSUE TITLE
Databáze

### ISSUE THREAD

**Issue by landsman** [manGoweb/MangoPress#75]
Neuvažovali jste o integraci VersionPress?
Jak řešíte nyní databázové migrace localhost vs. staging vs. produkce?

**Comment by enzy** [comment]
VersionPress nebyl stále připraven k našemu použití, ale třeba se situace změnila. Co @ViliamKopecky, bavil ses teď někdy s Borkem?

**Comment by landsman** [comment]
Rozumím, je to stále takové živé. Jak nyní řešíte synchronizaci dat, když něco připravíte na localhostu / stage, do produkce? Prochází to nějaký verzováním?
