### ISSUE TITLE
ACF

### ISSUE THREAD

**Issue by landsman** [manGoweb/MangoPress#77]
Použili jste to někdy s [ACF](https://www.advancedcustomfields.com/)?
Jak je to s kompatibilitou, supportem v latte?

**Comment by enzy** [comment]
Používáme https://metabox.io, které mají dopsanou přímo podporu pomocí `neon` konfigurace (složka `theme/define`)

**Comment by landsman** [comment]
Cool, díky!
Nedopíšem do Readme, sekce doporučované pluginy?
