### ISSUE TITLE
Vývoj - doc

### ISSUE THREAD

**Issue by landsman** [manGoweb/MangoPress#78]
Přemýšlím, jak to bude s vývojem na tomto stacku dál.

Tzn. když na tom postavím nyní web, uběhne rok, MangoPress se nějakým způsobe vyvine, opraví se třeba nějaké bugy, jak zanesu tyto úpravy jednoduše do mého projektu? 

Jak oddělím svůj kód (třeba šablonu) od MangoPress základu?

Uvažovali jste podobně?

díky

**Comment by landsman** [comment]
2) Máte nějaký doporučený plugin, co používáte pro cachování? Jsou tam nějaká specifika ohledně latte, invalidace?

**Comment by enzy** [comment]
> Tzn. když na tom postavím nyní web, uběhne rok, MangoPress se nějakým způsobe vyvine, opraví se třeba nějaké bugy, jak zanesu tyto úpravy jednoduše do mého projektu?

budeš si držet `manGoweb/MangoPress` jako remote a po roce si uděláš merge do své větve, či lépe cherry-pick commitů, které budou pro tebe relevantní.

>  Jsou tam nějaká specifika ohledně latte, invalidace?

Latte pouze generuje HTML výstup, stejně jako prostá PHP šablona. Takže potřeba není.

> Máte nějaký doporučený plugin, co používáte pro cachování?

Já používal [WP Super Cache](https://cs.wordpress.org/plugins/wp-super-cache/), ale nevyzkoušel jsem ji vlastně ještě na mangopressu. Nicméně chyba s MangoPress nesouvisí, spíše s devstackem.

**Comment by landsman** [comment]
No jde mi třeba právě o theme, nešlo by jej separovat tak, abych neupravoval něco, co je vlastně v repozitáři? Více oddělit MangoPress od mého kódu, rozumíme si?

**Comment by ViliamKopecky** [comment]
@landsman jo, více to oddělit je v plánu pro v2, ale nemám na to dost času 😀

A u toho pluginu u tech cest mi prijde zvlastni ze ma php soubory primo ve wp-content. Imho by mely byt ve slozce pluginu.
