### ISSUE TITLE
Nechceme default outline none

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/MangoPress#86]
https://github.com/manGoweb/MangoPress/blob/master/theme/styles/global.styl#L6-L8

@ViliamKopecky

**Comment by enzy** [comment]
Grafici to chtěj, přístupnosti to ale nepomáhá, s tím souhlasím.

**Comment by Onset** [comment]
Tak co použít `*:focus:not(:focusring)`? Brzy to snad bude mít i nějakou rozumnou podporu. Teď to bude alespoň pro pár browserů lepší než žádný outline.

**Comment by ViliamKopecky** [comment]
Ještě je taková ta možnost - vypnout/zapnout outlinování přes nějakou detekci v javascriptu - třeba když uživatel použije klávesu `tab`, tak povolit, nebo naopak pokud je mousemove, tak zakázat. Nebo to vymyslet ještě nějak sofistikovanějc.

https://www.paciellogroup.com/blog/2012/04/how-to-remove-css-outlines-in-an-accessible-manner/

**Comment by Onset** [comment]
Ten JavaScript dělá v podstatě to samé jako `:focusring`.
